[package]
name = "primitives"
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"
[dependencies]
serde = { workspace = true, features = ["derive"] }
rustc-hash = {workspace = true}
slab = {workspace = true, features = ["serde"]}
util = {version = "0.1.0", path = "../util"}

[dev-dependencies]
alloy = {workspace = true}
rmp-serde = {workspace = true}
solana-sdk = {workspace = true}
