[package]
name = "primitives"
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"
[dependencies]
rustc-hash = {workspace = true}
slab = {workspace = true, features = ["serde"]}
litemap = {workspace = true, features = ["serde"]}
serde = { workspace = true, features = ["derive"] }

util = {version = "0.1.0", path = "../util"}

[dev-dependencies]
rmp-serde = {workspace = true}
