use crate::message::hot_path::Trade;
use crate::message::side_path::ReplicationMsg;

/// Book state listener push the changes of the book to the remote components for state replication.
/// The implementation depends on the mode that the OMS engine running, Master or Slave.
pub type BookListener = Box<dyn Fn(&ReplicationMsg)>;

/// Trade listener push the trade event to the downstream component, it is run only by OMS_Master.
pub type TradeListener = Box<dyn Fn(&Vec<Trade>)>;

/// Listeners contains none blocking callback closures to notify book changes to the external system.
#[derive(Default)]
pub struct Listeners {
    /// Book state listener, it replicates the changes of the book to remote system.
    /// The listener running by OMS_Master replicates the changes to OMS_Slave via NATS stream,
    /// while the listener running by OMS_Slave replicates the changes to the Redis Cluster.
    book_listener: Option<BookListener>,

    /// Trade listener, ran only in OMS_Master, it pushes the trades generated by an
    /// execution to the SVD_Settlement.
    trade_listener: Option<TradeListener>,
}

impl Listeners {
    /// Set the book state listener.
    pub fn with_book_state_listener(mut self, book_listener: BookListener) -> Self {
        self.book_listener = Some(book_listener);
        self
    }

    /// Set the trade listener.
    pub fn with_trade_state_listener(mut self, trade_listener: TradeListener) -> Self {
        self.trade_listener = Some(trade_listener);
        self
    }

    /// Fanout replication messages.
    pub fn fanout_replication_msg(&self, replication_msg: &ReplicationMsg) {
        self.book_listener(replication_msg);
    }

    /// Fanout the trade event messages.
    pub fn fanout_trade_msg(&self, trades: &Vec<Trade>) {
        self.trade_listener(trades);
    }
}
